export const TrackExample = {
  artwork_url: 'https://i1.sndcdn.com/artworks-000139266154-uy5bid-large.jpg',
  caption: null,
  commentable: true,
  comment_count: 35,
  created_at: '2015-12-12T02:21:21Z',
  description: '',
  downloadable: false,
  download_count: 0,
  duration: 232746,
  full_duration: 232746,
  embeddable_by: 'all',
  genre: 'Session',
  has_downloads_left: false,
  id: 237178664,
  kind: 'track',
  label_name: null,
  last_modified: '2021-06-02T07:53:16Z',
  license: 'all-rights-reserved',
  likes_count: 4575,
  permalink: 'masterchiefer-x-tadoubledolla-x-idkjeffery',
  permalink_url:
    'https://soundcloud.com/jetwiley/masterchiefer-x-tadoubledolla-x-idkjeffery',
  playback_count: 307199,
  public: true,
  publisher_metadata: null,
  purchase_title: null,
  purchase_url: null,
  release_date: null,
  reposts_count: 382,
  secret_token: null,
  sharing: 'public',
  state: 'finished',
  streamable: true,
  tag_list: '2C0LD 2C0LDHOE UHHUH BANDZ',
  title: 'MasterChiefer x TADOUBLEDOLLA x IDKJEFFERY (Prod.DomoArygoto)',
  track_format: 'single-track',
  uri: 'https://api.soundcloud.com/tracks/237178664',
  urn: 'soundcloud:tracks:237178664',
  user_id: 30694728,
  visuals: null,
  waveform_url: 'https://wave.sndcdn.com/yc993VvYAEkB_m.json',
  display_date: '2015-12-12T02:21:21Z',
  media: {
    transcodings: [
      {
        url:
          'https://api-v2.soundcloud.com/media/soundcloud:tracks:237178664/aa608dee-54c5-40a1-901d-e7606bbacdaf/stream/hls',
        preset: 'mp3_0_0',
        duration: 232746,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/mpeg',
        },
        quality: 'sq',
      },
      {
        url:
          'https://api-v2.soundcloud.com/media/soundcloud:tracks:237178664/aa608dee-54c5-40a1-901d-e7606bbacdaf/stream/progressive',
        preset: 'mp3_0_0',
        duration: 232746,
        snipped: false,
        format: {
          protocol: 'progressive',
          mime_type: 'audio/mpeg',
        },
        quality: 'sq',
      },
      {
        url:
          'https://api-v2.soundcloud.com/media/soundcloud:tracks:237178664/ab6cbca9-b8e9-4a88-83a4-26ddb58b2756/stream/hls',
        preset: 'opus_0_0',
        duration: 232746,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/ogg; codecs="opus"',
        },
        quality: 'sq',
      },
    ],
  },
  station_urn: 'soundcloud:system-playlists:track-stations:237178664',
  station_permalink: 'track-stations:237178664',
  track_authorization:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjY0NjQ3MGRmLWZhZDUtNGU3NC1iM2M2LTc5ODA2YzRlY2UxOSIsImlhdCI6MTY0MTg4MzQxMH0.So4slS5uefsdwJoMYKKlptQhp1Fllpjh2NpolIERJ1g',
  monetization_model: 'NOT_APPLICABLE',
  policy: 'ALLOW',
  user: {
    avatar_url: 'https://i1.sndcdn.com/avatars-000353641226-72aw88-large.jpg',
    city: 'Houston',
    comments_count: 3,
    country_code: 'US',
    created_at: '2012-12-17T22:46:35Z',
    creator_subscriptions: [
      {
        product: {
          id: 'free',
        },
      },
    ],
    creator_subscription: {
      product: {
        id: 'free',
      },
    },
    description: '2C0LDHOE is ALL you need to kno!',
    followers_count: 548,
    followings_count: 91,
    first_name: 'Ryan',
    full_name: 'Ryan Wiley',
    groups_count: 0,
    id: 30694728,
    kind: 'user',
    last_modified: '2019-07-30T19:04:47Z',
    last_name: 'Wiley',
    likes_count: 660,
    playlist_likes_count: 14,
    permalink: 'jetwiley',
    permalink_url: 'https://soundcloud.com/jetwiley',
    playlist_count: 3,
    reposts_count: null,
    track_count: 35,
    uri: 'https://api.soundcloud.com/users/30694728',
    urn: 'soundcloud:users:30694728',
    username: 'Jet Wiley',
    verified: false,
    visuals: {
      urn: 'soundcloud:users:30694728',
      enabled: true,
      visuals: [
        {
          urn: 'soundcloud:visuals:38103763',
          entry_time: 0,
          visual_url:
            'https://i1.sndcdn.com/visuals-000030694728-hk4HWF-original.jpg',
        },
      ],
      tracking: null,
    },
    badges: {
      pro: false,
      pro_unlimited: false,
      verified: false,
    },
    station_urn: 'soundcloud:system-playlists:artist-stations:30694728',
    station_permalink: 'artist-stations:30694728',
  },
};

export const PlaylistExample = {
  artwork_url:
    'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
  created_at: '2021-12-03T01:50:37Z',
  description: 'BAD BOYS FOR LIFE!',
  duration: 1150301,
  embeddable_by: 'all',
  genre: 'Hip-hop & Rap',
  id: 1356721711,
  kind: 'playlist',
  label_name: '',
  last_modified: '2021-12-04T07:18:58Z',
  license: 'all-rights-reserved',
  likes_count: 815,
  managed_by_feeds: false,
  permalink: 'bad-boys-ii',
  permalink_url: 'https://soundcloud.com/idontknowjeffery/sets/bad-boys-ii',
  public: true,
  purchase_title: null,
  purchase_url: null,
  release_date: '2021-11-30T00:00:00Z',
  reposts_count: 94,
  secret_token: null,
  sharing: 'public',
  tag_list: 'abovethelawrecords healthyboyz empire badboys2',
  title: 'BAD BOYS II - idontknowjeffery & Eddy Baker',
  uri: 'https://api.soundcloud.com/playlists/1356721711',
  user_id: 55254934,
  set_type: '',
  is_album: false,
  published_at: '2021-12-03T01:50:37Z',
  display_date: '2021-12-03T01:50:37Z',
  user: {
    avatar_url:
      'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
    first_name: 'idontknowjeffery',
    followers_count: 72520,
    full_name: 'idontknowjeffery',
    id: 55254934,
    kind: 'user',
    last_modified: '2021-12-05T22:17:18Z',
    last_name: '',
    permalink: 'idontknowjeffery',
    permalink_url: 'https://soundcloud.com/idontknowjeffery',
    uri: 'https://api.soundcloud.com/users/55254934',
    urn: 'soundcloud:users:55254934',
    username: 'idontknowjeffery',
    verified: true,
    city: 'East Memphis',
    country_code: 'US',
    badges: {
      pro: false,
      pro_unlimited: true,
      verified: true,
    },
    station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
    station_permalink: 'artist-stations:55254934',
  },
  tracks: [
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 34,
      created_at: '2021-12-03T01:46:00Z',
      description: 'Prod. By BOZ',
      downloadable: false,
      download_count: 0,
      duration: 146442,
      full_duration: 146442,
      embeddable_by: 'all',
      genre: 'Hip-hop & Rap',
      has_downloads_left: false,
      id: 1170973903,
      kind: 'track',
      label_name: null,
      last_modified: '2021-12-16T05:02:36Z',
      license: 'all-rights-reserved',
      likes_count: 918,
      permalink: 'warzone-idontknowjeffery-eddy-baker',
      permalink_url:
        'https://soundcloud.com/idontknowjeffery/warzone-idontknowjeffery-eddy-baker',
      playback_count: 24239,
      public: true,
      publisher_metadata: {
        id: 1170973903,
        urn: 'soundcloud:tracks:1170973903',
        artist: 'idontknowjeffery',
        album_title: '                              ',
        contains_music: true,
        publisher: 'Jeffrey T Harper',
        isrc: 'QZTH82167763',
        explicit: true,
      },
      purchase_title: null,
      purchase_url: null,
      release_date: null,
      reposts_count: 37,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: 'abovethelawrecords healthyboyz empire badboys2',
      title: 'WARZONE - idontknowjeffery & Eddy Baker(Prod. By BOZ)',
      track_format: 'single-track',
      uri: 'https://api.soundcloud.com/tracks/1170973903',
      urn: 'soundcloud:tracks:1170973903',
      user_id: 55254934,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/PnVN3eCVnIsW_m.json',
      display_date: '2021-12-03T01:46:00Z',
      media: {
        transcodings: [
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973903/6a8a73bb-c8a5-4d62-beb7-e660888fc9e0/stream/hls',
            preset: 'mp3_0_1',
            duration: 146442,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973903/6a8a73bb-c8a5-4d62-beb7-e660888fc9e0/stream/progressive',
            preset: 'mp3_0_1',
            duration: 146442,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973903/0aa7ce1f-08c1-4215-ad57-48161243af6a/stream/hls',
            preset: 'opus_0_0',
            duration: 146423,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1170973903',
      station_permalink: 'track-stations:1170973903',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjhhNzQ5YmRhLTRkZTQtNGU4Yi05NGNkLTM2Y2M1MTQ1M2ViOCIsImlhdCI6MTY0MTg4MzQzMX0.bFj0xhXJj-mFKVajHKE9kGnIFOvPphbFLz6BYP3NcMs',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
        first_name: 'idontknowjeffery',
        followers_count: 72520,
        full_name: 'idontknowjeffery',
        id: 55254934,
        kind: 'user',
        last_modified: '2021-12-05T22:17:18Z',
        last_name: '',
        permalink: 'idontknowjeffery',
        permalink_url: 'https://soundcloud.com/idontknowjeffery',
        uri: 'https://api.soundcloud.com/users/55254934',
        urn: 'soundcloud:users:55254934',
        username: 'idontknowjeffery',
        verified: true,
        city: 'East Memphis',
        country_code: 'US',
        badges: {
          pro: false,
          pro_unlimited: true,
          verified: true,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
        station_permalink: 'artist-stations:55254934',
      },
    },
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 19,
      created_at: '2021-12-03T01:43:31Z',
      description: 'Prod. By BOZ',
      downloadable: false,
      download_count: 0,
      duration: 163213,
      full_duration: 163213,
      embeddable_by: 'all',
      genre: 'Hip-hop & Rap',
      has_downloads_left: false,
      id: 1170973024,
      kind: 'track',
      label_name: null,
      last_modified: '2021-12-07T05:42:36Z',
      license: 'all-rights-reserved',
      likes_count: 643,
      permalink: 'touched-idontknowjeffery-eddy-baker',
      permalink_url:
        'https://soundcloud.com/idontknowjeffery/touched-idontknowjeffery-eddy-baker',
      playback_count: 16118,
      public: true,
      publisher_metadata: {
        id: 1170973024,
        urn: 'soundcloud:tracks:1170973024',
        artist: 'idontknowjeffery',
        contains_music: true,
        publisher: 'Jeffrey T Harper',
        isrc: 'QZTH82167760',
        explicit: true,
      },
      purchase_title: null,
      purchase_url: null,
      release_date: null,
      reposts_count: 34,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: '"abovethelawrecords #healthyboyz #empire #badboys2"',
      title: 'TOUCHED - idontknowjeffery & Eddy Baker (Prod. By BOZ)',
      track_format: 'single-track',
      uri: 'https://api.soundcloud.com/tracks/1170973024',
      urn: 'soundcloud:tracks:1170973024',
      user_id: 55254934,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/VfNCMtdTMCWo_m.json',
      display_date: '2021-12-03T01:43:31Z',
      media: {
        transcodings: [
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973024/5c5a8d99-bc79-4bbd-82bb-a588dc192c2a/stream/hls',
            preset: 'mp3_0_1',
            duration: 163213,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973024/5c5a8d99-bc79-4bbd-82bb-a588dc192c2a/stream/progressive',
            preset: 'mp3_0_1',
            duration: 163213,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973024/5cb4d1ad-fdfb-4037-8e74-d80932489381/stream/hls',
            preset: 'opus_0_0',
            duration: 163183,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1170973024',
      station_permalink: 'track-stations:1170973024',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjIzMmQ1MzZjLTk1MzQtNGMwZC04NzBjLTE3ZGY3MWI5MTgxMiIsImlhdCI6MTY0MTg4MzQzMX0.68E7AHyf0NodtjBudYcmVdCc5yOe9qRHaBYURbmbmLg',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
        first_name: 'idontknowjeffery',
        followers_count: 72520,
        full_name: 'idontknowjeffery',
        id: 55254934,
        kind: 'user',
        last_modified: '2021-12-05T22:17:18Z',
        last_name: '',
        permalink: 'idontknowjeffery',
        permalink_url: 'https://soundcloud.com/idontknowjeffery',
        uri: 'https://api.soundcloud.com/users/55254934',
        urn: 'soundcloud:users:55254934',
        username: 'idontknowjeffery',
        verified: true,
        city: 'East Memphis',
        country_code: 'US',
        badges: {
          pro: false,
          pro_unlimited: true,
          verified: true,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
        station_permalink: 'artist-stations:55254934',
      },
    },
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 23,
      created_at: '2021-12-03T01:38:22Z',
      description: 'Prod. By Lyson Beats',
      downloadable: false,
      download_count: 0,
      duration: 128705,
      full_duration: 128705,
      embeddable_by: 'all',
      genre: 'Hip-hop & Rap',
      has_downloads_left: false,
      id: 1170970672,
      kind: 'track',
      label_name: null,
      last_modified: '2021-12-08T00:49:58Z',
      license: 'all-rights-reserved',
      likes_count: 686,
      permalink: 'dirty-cop-idontknowjeffery-eddy-baker',
      permalink_url:
        'https://soundcloud.com/idontknowjeffery/dirty-cop-idontknowjeffery-eddy-baker',
      playback_count: 19247,
      public: true,
      publisher_metadata: {
        id: 1170970672,
        urn: 'soundcloud:tracks:1170970672',
        artist: 'idontknowjeffery',
        album_title: '                              ',
        contains_music: true,
        publisher: 'Jeffrey T Harper',
        isrc: 'QZTH82167738',
        explicit: true,
      },
      purchase_title: null,
      purchase_url: null,
      release_date: null,
      reposts_count: 28,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: 'abovethelawrecords healthyboyz Empire Badboys2',
      title: 'DIRTY COP - idontknowjeffery & Eddy Baker (Prod. By Lyson Beats)',
      track_format: 'single-track',
      uri: 'https://api.soundcloud.com/tracks/1170970672',
      urn: 'soundcloud:tracks:1170970672',
      user_id: 55254934,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/Wgjc3sB6U7Wu_m.json',
      display_date: '2021-12-03T01:38:22Z',
      media: {
        transcodings: [
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170970672/74e08688-1f5b-4a8e-ad56-abca53e65153/stream/hls',
            preset: 'mp3_0_1',
            duration: 128705,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170970672/74e08688-1f5b-4a8e-ad56-abca53e65153/stream/progressive',
            preset: 'mp3_0_1',
            duration: 128705,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170970672/65de9657-1bf9-4df8-bd04-96114583cc4d/stream/hls',
            preset: 'opus_0_0',
            duration: 128686,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1170970672',
      station_permalink: 'track-stations:1170970672',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjYyOGUzNTViLTlhNWQtNDI1ZS05OTM5LTkzYWZlMGZiNWU4ZiIsImlhdCI6MTY0MTg4MzQzMX0.pcmxXwlzuUV2DL3cwG48pj8ksF8pzk-gSa7nrL9A8Dc',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
        first_name: 'idontknowjeffery',
        followers_count: 72520,
        full_name: 'idontknowjeffery',
        id: 55254934,
        kind: 'user',
        last_modified: '2021-12-05T22:17:18Z',
        last_name: '',
        permalink: 'idontknowjeffery',
        permalink_url: 'https://soundcloud.com/idontknowjeffery',
        uri: 'https://api.soundcloud.com/users/55254934',
        urn: 'soundcloud:users:55254934',
        username: 'idontknowjeffery',
        verified: true,
        city: 'East Memphis',
        country_code: 'US',
        badges: {
          pro: false,
          pro_unlimited: true,
          verified: true,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
        station_permalink: 'artist-stations:55254934',
      },
    },
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 14,
      created_at: '2021-12-03T01:34:42Z',
      description: 'Prod. By BOZ',
      downloadable: false,
      download_count: 0,
      duration: 130377,
      full_duration: 130377,
      embeddable_by: 'all',
      genre: 'Hip-hop & Rap',
      has_downloads_left: false,
      id: 1170969301,
      kind: 'track',
      label_name: null,
      last_modified: '2021-12-25T09:55:28Z',
      license: 'all-rights-reserved',
      likes_count: 598,
      permalink: 'choosing-fee-idontknowjeffery-eddy-baker',
      permalink_url:
        'https://soundcloud.com/idontknowjeffery/choosing-fee-idontknowjeffery-eddy-baker',
      playback_count: 16915,
      public: true,
      publisher_metadata: {
        id: 1170969301,
        urn: 'soundcloud:tracks:1170969301',
        artist: 'idontknowjeffery',
        contains_music: true,
        publisher: 'Jeffrey T Harper',
        isrc: 'QZTH82167734',
        explicit: true,
      },
      purchase_title: null,
      purchase_url: null,
      release_date: null,
      reposts_count: 32,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: 'abovethelawrecords healthyboyz Empire Badboys2',
      title: 'CHOOSING FEE - idontknowjeffery & Eddy Baker (Prod. By BOZ)',
      track_format: 'single-track',
      uri: 'https://api.soundcloud.com/tracks/1170969301',
      urn: 'soundcloud:tracks:1170969301',
      user_id: 55254934,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/TJUDBJTe4FkC_m.json',
      display_date: '2021-12-03T01:34:42Z',
      media: {
        transcodings: [
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170969301/51637923-d1b8-4d45-b7fa-22626078a7d1/stream/hls',
            preset: 'mp3_0_1',
            duration: 130377,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170969301/51637923-d1b8-4d45-b7fa-22626078a7d1/stream/progressive',
            preset: 'mp3_0_1',
            duration: 130377,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170969301/b6c474d5-6bea-497d-bc74-ee988b74ac93/stream/hls',
            preset: 'opus_0_0',
            duration: 130358,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1170969301',
      station_permalink: 'track-stations:1170969301',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjE4YjcwNGU2LTlmOWUtNGRmMS1hMTJlLTZiY2RhM2Q0MDQ0YiIsImlhdCI6MTY0MTg4MzQzMX0.Z0_ko2tNYlp8ElNZ7jtwY6pQC4AKdgFmPZPNOfgsLLU',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
        first_name: 'idontknowjeffery',
        followers_count: 72520,
        full_name: 'idontknowjeffery',
        id: 55254934,
        kind: 'user',
        last_modified: '2021-12-05T22:17:18Z',
        last_name: '',
        permalink: 'idontknowjeffery',
        permalink_url: 'https://soundcloud.com/idontknowjeffery',
        uri: 'https://api.soundcloud.com/users/55254934',
        urn: 'soundcloud:users:55254934',
        username: 'idontknowjeffery',
        verified: true,
        city: 'East Memphis',
        country_code: 'US',
        badges: {
          pro: false,
          pro_unlimited: true,
          verified: true,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
        station_permalink: 'artist-stations:55254934',
      },
    },
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 7,
      created_at: '2021-12-03T01:49:39Z',
      description: 'Prod. By Quintin Lamb',
      downloadable: false,
      download_count: 0,
      duration: 105143,
      full_duration: 105143,
      embeddable_by: 'all',
      genre: 'Hip-hop & Rap',
      has_downloads_left: false,
      id: 1170975193,
      kind: 'track',
      label_name: null,
      last_modified: '2022-01-06T03:17:02Z',
      license: 'all-rights-reserved',
      likes_count: 350,
      permalink: 'the-predator-eddy-baker',
      permalink_url:
        'https://soundcloud.com/idontknowjeffery/the-predator-eddy-baker',
      playback_count: 11106,
      public: true,
      publisher_metadata: {
        id: 1170975193,
        urn: 'soundcloud:tracks:1170975193',
        artist: 'Eddy Baker',
        contains_music: true,
        publisher: 'Jamaal Ashby',
        isrc: 'QZTH82167770',
        explicit: true,
      },
      purchase_title: null,
      purchase_url: null,
      release_date: null,
      reposts_count: 11,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: 'abovethelawrecords healthyboyz empire badboys2',
      title: 'THE PREDATOR - Eddy Baker (Prod. By Quintin Lamb)',
      track_format: 'single-track',
      uri: 'https://api.soundcloud.com/tracks/1170975193',
      urn: 'soundcloud:tracks:1170975193',
      user_id: 55254934,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/KhoEDHM41qia_m.json',
      display_date: '2021-12-03T01:49:39Z',
      media: {
        transcodings: [
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170975193/365e18c3-c2c6-4545-b65b-dc580617eaad/stream/hls',
            preset: 'mp3_0_1',
            duration: 105143,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170975193/365e18c3-c2c6-4545-b65b-dc580617eaad/stream/progressive',
            preset: 'mp3_0_1',
            duration: 105143,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170975193/e95084b4-e9fc-444e-9461-0db3569173e7/stream/hls',
            preset: 'opus_0_0',
            duration: 105122,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1170975193',
      station_permalink: 'track-stations:1170975193',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjEwZGQ1YjdjLTRhYzAtNDgxZC1hYzQ0LWMxNDNmNmIyZTY3NyIsImlhdCI6MTY0MTg4MzQzMX0.jXOTKPvmMPR7cAm9ZAzOcPye0IuHV_bJFpP9PcP4v9U',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
        first_name: 'idontknowjeffery',
        followers_count: 72520,
        full_name: 'idontknowjeffery',
        id: 55254934,
        kind: 'user',
        last_modified: '2021-12-05T22:17:18Z',
        last_name: '',
        permalink: 'idontknowjeffery',
        permalink_url: 'https://soundcloud.com/idontknowjeffery',
        uri: 'https://api.soundcloud.com/users/55254934',
        urn: 'soundcloud:users:55254934',
        username: 'idontknowjeffery',
        verified: true,
        city: 'East Memphis',
        country_code: 'US',
        badges: {
          pro: false,
          pro_unlimited: true,
          verified: true,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
        station_permalink: 'artist-stations:55254934',
      },
    },
    {
      id: 1170966667,
      kind: 'track',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
    },
    {
      id: 1170965671,
      kind: 'track',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
    },
    {
      id: 1170963832,
      kind: 'track',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
    },
  ],
  track_count: 8,
};

export const PlaylistsTrackExample = {
  artwork_url:
    'https://i1.sndcdn.com/artworks-FCAyzXS08gNYlLOX-vlGTuQ-large.jpg',
  caption: null,
  commentable: true,
  comment_count: 44,
  created_at: '2021-02-11T01:37:51Z',
  description: '',
  downloadable: false,
  download_count: 0,
  duration: 204826,
  full_duration: 204826,
  embeddable_by: 'all',
  genre: 'Hip-hop & Rap',
  has_downloads_left: false,
  id: 983132659,
  kind: 'track',
  label_name: null,
  last_modified: '2021-08-16T03:49:37Z',
  license: 'all-rights-reserved',
  likes_count: 1189,
  permalink: 'damn-i-love-revenge',
  permalink_url: 'https://soundcloud.com/idontknowjeffery/damn-i-love-revenge',
  playback_count: 66599,
  public: true,
  publisher_metadata: {
    id: 983132659,
    urn: 'soundcloud:tracks:983132659',
    artist: 'idontknowjeffery',
    contains_music: true,
    publisher: 'Jeffrey T Harper',
    isrc: 'QZF8N2131277',
    explicit: true,
  },
  purchase_title: null,
  purchase_url: null,
  release_date: null,
  reposts_count: 52,
  secret_token: null,
  sharing: 'public',
  state: 'finished',
  streamable: true,
  tag_list: '',
  title: 'DAMN I LOVE REVENGE (Prod. by Quintin Lamb)',
  track_format: 'single-track',
  uri: 'https://api.soundcloud.com/tracks/983132659',
  urn: 'soundcloud:tracks:983132659',
  user_id: 55254934,
  visuals: null,
  waveform_url: 'https://wave.sndcdn.com/raJ1cEDRJVBd_m.json',
  display_date: '2021-02-14T08:28:17Z',
  media: {
    transcodings: [
      {
        url:
          'https://api-v2.soundcloud.com/media/soundcloud:tracks:983132659/d4247702-e191-4168-8df6-022604ed97f7/stream/hls',
        preset: 'mp3_0_1',
        duration: 204826,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/mpeg',
        },
        quality: 'sq',
      },
      {
        url:
          'https://api-v2.soundcloud.com/media/soundcloud:tracks:983132659/d4247702-e191-4168-8df6-022604ed97f7/stream/progressive',
        preset: 'mp3_0_1',
        duration: 204826,
        snipped: false,
        format: {
          protocol: 'progressive',
          mime_type: 'audio/mpeg',
        },
        quality: 'sq',
      },
      {
        url:
          'https://api-v2.soundcloud.com/media/soundcloud:tracks:983132659/7b469350-8045-4788-990b-5fbaa602c1b9/stream/hls',
        preset: 'opus_0_0',
        duration: 204782,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/ogg; codecs="opus"',
        },
        quality: 'sq',
      },
    ],
  },
  station_urn: 'soundcloud:system-playlists:track-stations:983132659',
  station_permalink: 'track-stations:983132659',
  track_authorization:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjE3NzE5NDY2LTAwZmQtNDZiZS1iZTRiLWVkZjFiYTFhNzllZiIsImlhdCI6MTY0MTg4MzQzMH0.JzgBaeDVuOhmRuDI-eoJWA8jTIY7iFO-19JrMyomSxc',
  monetization_model: 'NOT_APPLICABLE',
  policy: 'ALLOW',
  user: {
    avatar_url:
      'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
    first_name: 'idontknowjeffery',
    followers_count: 72520,
    full_name: 'idontknowjeffery',
    id: 55254934,
    kind: 'user',
    last_modified: '2021-12-05T22:17:18Z',
    last_name: '',
    permalink: 'idontknowjeffery',
    permalink_url: 'https://soundcloud.com/idontknowjeffery',
    uri: 'https://api.soundcloud.com/users/55254934',
    urn: 'soundcloud:users:55254934',
    username: 'idontknowjeffery',
    verified: true,
    city: 'East Memphis',
    country_code: 'US',
    badges: {
      pro: false,
      pro_unlimited: true,
      verified: true,
    },
    station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
    station_permalink: 'artist-stations:55254934',
  },
};

export const UsersTrackExample = {
  artwork_url:
    'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
  caption: null,
  commentable: true,
  comment_count: 7,
  created_at: '2021-12-03T01:49:39Z',
  description: 'Prod. By Quintin Lamb',
  downloadable: false,
  download_count: 0,
  duration: 105143,
  full_duration: 105143,
  embeddable_by: 'all',
  genre: 'Hip-hop & Rap',
  has_downloads_left: false,
  id: 1170975193,
  kind: 'track',
  label_name: null,
  last_modified: '2022-01-06T03:17:02Z',
  license: 'all-rights-reserved',
  likes_count: 350,
  permalink: 'the-predator-eddy-baker',
  permalink_url:
    'https://soundcloud.com/idontknowjeffery/the-predator-eddy-baker',
  playback_count: 11106,
  public: true,
  publisher_metadata: {
    id: 1170975193,
    urn: 'soundcloud:tracks:1170975193',
    artist: 'Eddy Baker',
    contains_music: true,
    publisher: 'Jamaal Ashby',
    isrc: 'QZTH82167770',
    explicit: true,
  },
  purchase_title: null,
  purchase_url: null,
  release_date: null,
  reposts_count: 11,
  secret_token: null,
  sharing: 'public',
  state: 'finished',
  streamable: true,
  tag_list: 'abovethelawrecords healthyboyz empire badboys2',
  title: 'THE PREDATOR - Eddy Baker (Prod. By Quintin Lamb)',
  track_format: 'single-track',
  uri: 'https://api.soundcloud.com/tracks/1170975193',
  urn: 'soundcloud:tracks:1170975193',
  user_id: 55254934,
  visuals: null,
  waveform_url: 'https://wave.sndcdn.com/KhoEDHM41qia_m.json',
  display_date: '2021-12-03T01:49:39Z',
  media: {
    transcodings: [
      {
        url:
          'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170975193/365e18c3-c2c6-4545-b65b-dc580617eaad/stream/hls',
        preset: 'mp3_0_1',
        duration: 105143,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/mpeg',
        },
        quality: 'sq',
      },
      {
        url:
          'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170975193/365e18c3-c2c6-4545-b65b-dc580617eaad/stream/progressive',
        preset: 'mp3_0_1',
        duration: 105143,
        snipped: false,
        format: {
          protocol: 'progressive',
          mime_type: 'audio/mpeg',
        },
        quality: 'sq',
      },
      {
        url:
          'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170975193/e95084b4-e9fc-444e-9461-0db3569173e7/stream/hls',
        preset: 'opus_0_0',
        duration: 105122,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/ogg; codecs="opus"',
        },
        quality: 'sq',
      },
    ],
  },
  station_urn: 'soundcloud:system-playlists:track-stations:1170975193',
  station_permalink: 'track-stations:1170975193',
  track_authorization:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjEwZGQ1YjdjLTRhYzAtNDgxZC1hYzQ0LWMxNDNmNmIyZTY3NyIsImlhdCI6MTY0MTg4MzQzMX0.jXOTKPvmMPR7cAm9ZAzOcPye0IuHV_bJFpP9PcP4v9U',
  monetization_model: 'NOT_APPLICABLE',
  policy: 'ALLOW',
  user: {
    avatar_url:
      'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
    first_name: 'idontknowjeffery',
    followers_count: 72520,
    full_name: 'idontknowjeffery',
    id: 55254934,
    kind: 'user',
    last_modified: '2021-12-05T22:17:18Z',
    last_name: '',
    permalink: 'idontknowjeffery',
    permalink_url: 'https://soundcloud.com/idontknowjeffery',
    uri: 'https://api.soundcloud.com/users/55254934',
    urn: 'soundcloud:users:55254934',
    username: 'idontknowjeffery',
    verified: true,
    city: 'East Memphis',
    country_code: 'US',
    badges: {
      pro: false,
      pro_unlimited: true,
      verified: true,
    },
    station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
    station_permalink: 'artist-stations:55254934',
  },
};

export const UsersPlaylistExample = {
  artwork_url:
    'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
  created_at: '2021-12-03T01:50:37Z',
  description: 'BAD BOYS FOR LIFE!',
  duration: 1150301,
  embeddable_by: 'all',
  genre: 'Hip-hop & Rap',
  id: 1356721711,
  kind: 'playlist',
  label_name: '',
  last_modified: '2021-12-04T07:18:58Z',
  license: 'all-rights-reserved',
  likes_count: 815,
  managed_by_feeds: false,
  permalink: 'bad-boys-ii',
  permalink_url: 'https://soundcloud.com/idontknowjeffery/sets/bad-boys-ii',
  public: true,
  purchase_title: null,
  purchase_url: null,
  release_date: '2021-11-30T00:00:00Z',
  reposts_count: 94,
  secret_token: null,
  sharing: 'public',
  tag_list: 'abovethelawrecords healthyboyz empire badboys2',
  title: 'BAD BOYS II - idontknowjeffery & Eddy Baker',
  uri: 'https://api.soundcloud.com/playlists/1356721711',
  user_id: 55254934,
  set_type: '',
  is_album: false,
  published_at: '2021-12-03T01:50:37Z',
  display_date: '2021-12-03T01:50:37Z',
  user: {
    avatar_url:
      'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
    first_name: 'idontknowjeffery',
    followers_count: 72520,
    full_name: 'idontknowjeffery',
    id: 55254934,
    kind: 'user',
    last_modified: '2021-12-05T22:17:18Z',
    last_name: '',
    permalink: 'idontknowjeffery',
    permalink_url: 'https://soundcloud.com/idontknowjeffery',
    uri: 'https://api.soundcloud.com/users/55254934',
    urn: 'soundcloud:users:55254934',
    username: 'idontknowjeffery',
    verified: true,
    city: 'East Memphis',
    country_code: 'US',
    badges: {
      pro: false,
      pro_unlimited: true,
      verified: true,
    },
    station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
    station_permalink: 'artist-stations:55254934',
  },
  tracks: [
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 34,
      created_at: '2021-12-03T01:46:00Z',
      description: 'Prod. By BOZ',
      downloadable: false,
      download_count: 0,
      duration: 146442,
      full_duration: 146442,
      embeddable_by: 'all',
      genre: 'Hip-hop & Rap',
      has_downloads_left: false,
      id: 1170973903,
      kind: 'track',
      label_name: null,
      last_modified: '2021-12-16T05:02:36Z',
      license: 'all-rights-reserved',
      likes_count: 918,
      permalink: 'warzone-idontknowjeffery-eddy-baker',
      permalink_url:
        'https://soundcloud.com/idontknowjeffery/warzone-idontknowjeffery-eddy-baker',
      playback_count: 24239,
      public: true,
      publisher_metadata: {
        id: 1170973903,
        urn: 'soundcloud:tracks:1170973903',
        artist: 'idontknowjeffery',
        album_title: '                              ',
        contains_music: true,
        publisher: 'Jeffrey T Harper',
        isrc: 'QZTH82167763',
        explicit: true,
      },
      purchase_title: null,
      purchase_url: null,
      release_date: null,
      reposts_count: 37,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: 'abovethelawrecords healthyboyz empire badboys2',
      title: 'WARZONE - idontknowjeffery & Eddy Baker(Prod. By BOZ)',
      track_format: 'single-track',
      uri: 'https://api.soundcloud.com/tracks/1170973903',
      urn: 'soundcloud:tracks:1170973903',
      user_id: 55254934,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/PnVN3eCVnIsW_m.json',
      display_date: '2021-12-03T01:46:00Z',
      media: {
        transcodings: [
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973903/6a8a73bb-c8a5-4d62-beb7-e660888fc9e0/stream/hls',
            preset: 'mp3_0_1',
            duration: 146442,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973903/6a8a73bb-c8a5-4d62-beb7-e660888fc9e0/stream/progressive',
            preset: 'mp3_0_1',
            duration: 146442,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973903/0aa7ce1f-08c1-4215-ad57-48161243af6a/stream/hls',
            preset: 'opus_0_0',
            duration: 146423,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1170973903',
      station_permalink: 'track-stations:1170973903',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjhhNzQ5YmRhLTRkZTQtNGU4Yi05NGNkLTM2Y2M1MTQ1M2ViOCIsImlhdCI6MTY0MTg4MzQzMX0.bFj0xhXJj-mFKVajHKE9kGnIFOvPphbFLz6BYP3NcMs',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
        first_name: 'idontknowjeffery',
        followers_count: 72520,
        full_name: 'idontknowjeffery',
        id: 55254934,
        kind: 'user',
        last_modified: '2021-12-05T22:17:18Z',
        last_name: '',
        permalink: 'idontknowjeffery',
        permalink_url: 'https://soundcloud.com/idontknowjeffery',
        uri: 'https://api.soundcloud.com/users/55254934',
        urn: 'soundcloud:users:55254934',
        username: 'idontknowjeffery',
        verified: true,
        city: 'East Memphis',
        country_code: 'US',
        badges: {
          pro: false,
          pro_unlimited: true,
          verified: true,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
        station_permalink: 'artist-stations:55254934',
      },
    },
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 19,
      created_at: '2021-12-03T01:43:31Z',
      description: 'Prod. By BOZ',
      downloadable: false,
      download_count: 0,
      duration: 163213,
      full_duration: 163213,
      embeddable_by: 'all',
      genre: 'Hip-hop & Rap',
      has_downloads_left: false,
      id: 1170973024,
      kind: 'track',
      label_name: null,
      last_modified: '2021-12-07T05:42:36Z',
      license: 'all-rights-reserved',
      likes_count: 643,
      permalink: 'touched-idontknowjeffery-eddy-baker',
      permalink_url:
        'https://soundcloud.com/idontknowjeffery/touched-idontknowjeffery-eddy-baker',
      playback_count: 16118,
      public: true,
      publisher_metadata: {
        id: 1170973024,
        urn: 'soundcloud:tracks:1170973024',
        artist: 'idontknowjeffery',
        contains_music: true,
        publisher: 'Jeffrey T Harper',
        isrc: 'QZTH82167760',
        explicit: true,
      },
      purchase_title: null,
      purchase_url: null,
      release_date: null,
      reposts_count: 34,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: '"abovethelawrecords #healthyboyz #empire #badboys2"',
      title: 'TOUCHED - idontknowjeffery & Eddy Baker (Prod. By BOZ)',
      track_format: 'single-track',
      uri: 'https://api.soundcloud.com/tracks/1170973024',
      urn: 'soundcloud:tracks:1170973024',
      user_id: 55254934,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/VfNCMtdTMCWo_m.json',
      display_date: '2021-12-03T01:43:31Z',
      media: {
        transcodings: [
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973024/5c5a8d99-bc79-4bbd-82bb-a588dc192c2a/stream/hls',
            preset: 'mp3_0_1',
            duration: 163213,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973024/5c5a8d99-bc79-4bbd-82bb-a588dc192c2a/stream/progressive',
            preset: 'mp3_0_1',
            duration: 163213,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170973024/5cb4d1ad-fdfb-4037-8e74-d80932489381/stream/hls',
            preset: 'opus_0_0',
            duration: 163183,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1170973024',
      station_permalink: 'track-stations:1170973024',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjIzMmQ1MzZjLTk1MzQtNGMwZC04NzBjLTE3ZGY3MWI5MTgxMiIsImlhdCI6MTY0MTg4MzQzMX0.68E7AHyf0NodtjBudYcmVdCc5yOe9qRHaBYURbmbmLg',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
        first_name: 'idontknowjeffery',
        followers_count: 72520,
        full_name: 'idontknowjeffery',
        id: 55254934,
        kind: 'user',
        last_modified: '2021-12-05T22:17:18Z',
        last_name: '',
        permalink: 'idontknowjeffery',
        permalink_url: 'https://soundcloud.com/idontknowjeffery',
        uri: 'https://api.soundcloud.com/users/55254934',
        urn: 'soundcloud:users:55254934',
        username: 'idontknowjeffery',
        verified: true,
        city: 'East Memphis',
        country_code: 'US',
        badges: {
          pro: false,
          pro_unlimited: true,
          verified: true,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
        station_permalink: 'artist-stations:55254934',
      },
    },
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 23,
      created_at: '2021-12-03T01:38:22Z',
      description: 'Prod. By Lyson Beats',
      downloadable: false,
      download_count: 0,
      duration: 128705,
      full_duration: 128705,
      embeddable_by: 'all',
      genre: 'Hip-hop & Rap',
      has_downloads_left: false,
      id: 1170970672,
      kind: 'track',
      label_name: null,
      last_modified: '2021-12-08T00:49:58Z',
      license: 'all-rights-reserved',
      likes_count: 686,
      permalink: 'dirty-cop-idontknowjeffery-eddy-baker',
      permalink_url:
        'https://soundcloud.com/idontknowjeffery/dirty-cop-idontknowjeffery-eddy-baker',
      playback_count: 19247,
      public: true,
      publisher_metadata: {
        id: 1170970672,
        urn: 'soundcloud:tracks:1170970672',
        artist: 'idontknowjeffery',
        album_title: '                              ',
        contains_music: true,
        publisher: 'Jeffrey T Harper',
        isrc: 'QZTH82167738',
        explicit: true,
      },
      purchase_title: null,
      purchase_url: null,
      release_date: null,
      reposts_count: 28,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: 'abovethelawrecords healthyboyz Empire Badboys2',
      title: 'DIRTY COP - idontknowjeffery & Eddy Baker (Prod. By Lyson Beats)',
      track_format: 'single-track',
      uri: 'https://api.soundcloud.com/tracks/1170970672',
      urn: 'soundcloud:tracks:1170970672',
      user_id: 55254934,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/Wgjc3sB6U7Wu_m.json',
      display_date: '2021-12-03T01:38:22Z',
      media: {
        transcodings: [
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170970672/74e08688-1f5b-4a8e-ad56-abca53e65153/stream/hls',
            preset: 'mp3_0_1',
            duration: 128705,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170970672/74e08688-1f5b-4a8e-ad56-abca53e65153/stream/progressive',
            preset: 'mp3_0_1',
            duration: 128705,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170970672/65de9657-1bf9-4df8-bd04-96114583cc4d/stream/hls',
            preset: 'opus_0_0',
            duration: 128686,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1170970672',
      station_permalink: 'track-stations:1170970672',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjYyOGUzNTViLTlhNWQtNDI1ZS05OTM5LTkzYWZlMGZiNWU4ZiIsImlhdCI6MTY0MTg4MzQzMX0.pcmxXwlzuUV2DL3cwG48pj8ksF8pzk-gSa7nrL9A8Dc',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
        first_name: 'idontknowjeffery',
        followers_count: 72520,
        full_name: 'idontknowjeffery',
        id: 55254934,
        kind: 'user',
        last_modified: '2021-12-05T22:17:18Z',
        last_name: '',
        permalink: 'idontknowjeffery',
        permalink_url: 'https://soundcloud.com/idontknowjeffery',
        uri: 'https://api.soundcloud.com/users/55254934',
        urn: 'soundcloud:users:55254934',
        username: 'idontknowjeffery',
        verified: true,
        city: 'East Memphis',
        country_code: 'US',
        badges: {
          pro: false,
          pro_unlimited: true,
          verified: true,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
        station_permalink: 'artist-stations:55254934',
      },
    },
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 14,
      created_at: '2021-12-03T01:34:42Z',
      description: 'Prod. By BOZ',
      downloadable: false,
      download_count: 0,
      duration: 130377,
      full_duration: 130377,
      embeddable_by: 'all',
      genre: 'Hip-hop & Rap',
      has_downloads_left: false,
      id: 1170969301,
      kind: 'track',
      label_name: null,
      last_modified: '2021-12-25T09:55:28Z',
      license: 'all-rights-reserved',
      likes_count: 598,
      permalink: 'choosing-fee-idontknowjeffery-eddy-baker',
      permalink_url:
        'https://soundcloud.com/idontknowjeffery/choosing-fee-idontknowjeffery-eddy-baker',
      playback_count: 16915,
      public: true,
      publisher_metadata: {
        id: 1170969301,
        urn: 'soundcloud:tracks:1170969301',
        artist: 'idontknowjeffery',
        contains_music: true,
        publisher: 'Jeffrey T Harper',
        isrc: 'QZTH82167734',
        explicit: true,
      },
      purchase_title: null,
      purchase_url: null,
      release_date: null,
      reposts_count: 32,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: 'abovethelawrecords healthyboyz Empire Badboys2',
      title: 'CHOOSING FEE - idontknowjeffery & Eddy Baker (Prod. By BOZ)',
      track_format: 'single-track',
      uri: 'https://api.soundcloud.com/tracks/1170969301',
      urn: 'soundcloud:tracks:1170969301',
      user_id: 55254934,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/TJUDBJTe4FkC_m.json',
      display_date: '2021-12-03T01:34:42Z',
      media: {
        transcodings: [
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170969301/51637923-d1b8-4d45-b7fa-22626078a7d1/stream/hls',
            preset: 'mp3_0_1',
            duration: 130377,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170969301/51637923-d1b8-4d45-b7fa-22626078a7d1/stream/progressive',
            preset: 'mp3_0_1',
            duration: 130377,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170969301/b6c474d5-6bea-497d-bc74-ee988b74ac93/stream/hls',
            preset: 'opus_0_0',
            duration: 130358,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1170969301',
      station_permalink: 'track-stations:1170969301',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjE4YjcwNGU2LTlmOWUtNGRmMS1hMTJlLTZiY2RhM2Q0MDQ0YiIsImlhdCI6MTY0MTg4MzQzMX0.Z0_ko2tNYlp8ElNZ7jtwY6pQC4AKdgFmPZPNOfgsLLU',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
        first_name: 'idontknowjeffery',
        followers_count: 72520,
        full_name: 'idontknowjeffery',
        id: 55254934,
        kind: 'user',
        last_modified: '2021-12-05T22:17:18Z',
        last_name: '',
        permalink: 'idontknowjeffery',
        permalink_url: 'https://soundcloud.com/idontknowjeffery',
        uri: 'https://api.soundcloud.com/users/55254934',
        urn: 'soundcloud:users:55254934',
        username: 'idontknowjeffery',
        verified: true,
        city: 'East Memphis',
        country_code: 'US',
        badges: {
          pro: false,
          pro_unlimited: true,
          verified: true,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
        station_permalink: 'artist-stations:55254934',
      },
    },
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-QHuCGOmF6TCqzLdB-FyMuKw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 7,
      created_at: '2021-12-03T01:49:39Z',
      description: 'Prod. By Quintin Lamb',
      downloadable: false,
      download_count: 0,
      duration: 105143,
      full_duration: 105143,
      embeddable_by: 'all',
      genre: 'Hip-hop & Rap',
      has_downloads_left: false,
      id: 1170975193,
      kind: 'track',
      label_name: null,
      last_modified: '2022-01-06T03:17:02Z',
      license: 'all-rights-reserved',
      likes_count: 350,
      permalink: 'the-predator-eddy-baker',
      permalink_url:
        'https://soundcloud.com/idontknowjeffery/the-predator-eddy-baker',
      playback_count: 11106,
      public: true,
      publisher_metadata: {
        id: 1170975193,
        urn: 'soundcloud:tracks:1170975193',
        artist: 'Eddy Baker',
        contains_music: true,
        publisher: 'Jamaal Ashby',
        isrc: 'QZTH82167770',
        explicit: true,
      },
      purchase_title: null,
      purchase_url: null,
      release_date: null,
      reposts_count: 11,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: 'abovethelawrecords healthyboyz empire badboys2',
      title: 'THE PREDATOR - Eddy Baker (Prod. By Quintin Lamb)',
      track_format: 'single-track',
      uri: 'https://api.soundcloud.com/tracks/1170975193',
      urn: 'soundcloud:tracks:1170975193',
      user_id: 55254934,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/KhoEDHM41qia_m.json',
      display_date: '2021-12-03T01:49:39Z',
      media: {
        transcodings: [
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170975193/365e18c3-c2c6-4545-b65b-dc580617eaad/stream/hls',
            preset: 'mp3_0_1',
            duration: 105143,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170975193/365e18c3-c2c6-4545-b65b-dc580617eaad/stream/progressive',
            preset: 'mp3_0_1',
            duration: 105143,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
          },
          {
            url:
              'https://api-v2.soundcloud.com/media/soundcloud:tracks:1170975193/e95084b4-e9fc-444e-9461-0db3569173e7/stream/hls',
            preset: 'opus_0_0',
            duration: 105122,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1170975193',
      station_permalink: 'track-stations:1170975193',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJIUiIsInN1YiI6IiIsInJpZCI6IjEwZGQ1YjdjLTRhYzAtNDgxZC1hYzQ0LWMxNDNmNmIyZTY3NyIsImlhdCI6MTY0MTg4MzQzMX0.jXOTKPvmMPR7cAm9ZAzOcPye0IuHV_bJFpP9PcP4v9U',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-NhrUICnsAhcj87UZ-TgwlZg-large.jpg',
        first_name: 'idontknowjeffery',
        followers_count: 72520,
        full_name: 'idontknowjeffery',
        id: 55254934,
        kind: 'user',
        last_modified: '2021-12-05T22:17:18Z',
        last_name: '',
        permalink: 'idontknowjeffery',
        permalink_url: 'https://soundcloud.com/idontknowjeffery',
        uri: 'https://api.soundcloud.com/users/55254934',
        urn: 'soundcloud:users:55254934',
        username: 'idontknowjeffery',
        verified: true,
        city: 'East Memphis',
        country_code: 'US',
        badges: {
          pro: false,
          pro_unlimited: true,
          verified: true,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:55254934',
        station_permalink: 'artist-stations:55254934',
      },
    },
    {
      id: 1170966667,
      kind: 'track',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
    },
    {
      id: 1170965671,
      kind: 'track',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
    },
    {
      id: 1170963832,
      kind: 'track',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
    },
  ],
  track_count: 8,
};

export const SuggestionExample = {
  output: 'idkjeffery rape rape',
  query: 'idkjeffery rape rape',
};
